### ISSUE TITLE
【2019.12.18源码】

### ISSUE THREAD

**Issue by wefuxkgfw** [Lienol/openwrt-actions#2]
老哥你编译的x64固件貌似是uefi启动也一起加进去了，软路由系统启动时需要显示器键盘手动选择启动哪个。。（很多人是养成以前使用大雕的固件的习惯，直接默认启动单一一个的，他们没有显示器键盘，大雕的源码生成固件貌似是单独都分开的，uefi启动的x64，普通启动的x64）希望您能也分开不同启动方式的为单独的一个固件，刷完无需外设直接能访问后台使用。（带着一个显示器和键盘、还有软路由到处出差旅行，也不现实，您看是不是）请考虑，谢谢。

**Comment by Lienol** [comment]
并没有UEFI，自行解决

**Comment by wefuxkgfw** [comment]
> 并没有UEFI，自行解决

没有就没有没吧。但是的确需要接键盘和显示器回车才能启动固件系统。。。。。这是悟空的日常老哥亲测的，告诉我反馈给你。
